#CURSO DE PYTHON PARA INICIANTES

#APRESENTAÇÃO DO CURSO
#BAIXAR E INSTALAR PYTHON
#1° OLA MUNDO
#2° VARIAVEIS
#3° ENTRADA
#4° SAIDA
#5° OPERADORES
#6° CONDICIONAIS
#7° REPETIÇÃO WHILE
#8° REPETIÇÃO FOR
#9° LISTA
#10° MATRIZES
# PROGETO FINAL DO PRIMEIRO MODULO
